### PR TITLE
put anchor before text in tables

### PR DESCRIPTION
**Pull request by maxiloc**

### CODE REVIEW

**Comment by redox** [comment]
@maxiloc did you see my review? Why was `rb-readline` required?

**Comment by alexandremeunier** [comment]
@redox I think it was required for MacOs Sierra

**Comment by redox** [comment]
> @redox I think it was required for MacOs Sierra

:trollface:

**Comment by maxiloc** [comment]
Yes we also added it to AlgoliaWeb 😄

**Pull request merged**
